### ISSUE TITLE
-name has to allow duplicate keys. 

### ISSUE THREAD

**Issue by chappy2** [juanmi108/Super-Global-Hyper-Mega-Net-nosql#27]
Currently only the test@test.de user can create the standard lsit. All other users can't create the work and private backlog, because a user already have them. The Current dAy can only assigned to the first user, who is logged in first at that day.

E11000 duplicate key error index: superglobalhypermeganet.lists.$_name_1 dup key: { : "26.12 Saturday" }
E11000 duplicate key error index: superglobalhypermeganet.lists.$_name_1 dup key: { : "Work Backlog" }
E11000 duplicate key error index: superglobalhypermeganet.lists.$_name_1 dup key: { : "Private Backlog"

**Comment by juanmi108** [comment]
realted to #15

**Comment by juanmi108** [comment]
fixed by #28 and 863abfc

**Comment by juanmi108** [comment]
still not fixed

**Comment by juanmi108** [comment]
after some extensive looking, it turns out the problem lies in the angular controller. 

It just sends a post to  /list/:id where ":id" should not be the literal string ':id' but the ID of the name of the list.... 

```javascript
   .factory('ListsEdit', function($resource) {
 return $resource('/list/:id',{},{
      query: {method:'GET',isArray:false},
      update:{method:'POST',isArray:false}
      
  }); 
```

the route list/:id as a literal, does not exist and the request defaulted to post /list where a new object was created witch of course triggered a duplicated key exception.

**Comment by chappy2** [comment]
so :id is _id instead of _name?

**Comment by juanmi108** [comment]
:id is _name

**Comment by chappy2** [comment]
but that didn't work

**Comment by juanmi108** [comment]
I did not say replace :id with _name I said that :id needs :id needs to be replaced with the name of the list on each request. example:

get /list/backlog
get /list/worklog

**Comment by chappy2** [comment]
oh my good. sry. i fixed it... i merge it tomorrow ^^

**Comment by juanmi108** [comment]
thanks :) :+1:

**Comment by chappy2** [comment]
Okay im sorry, but i have to reopen it. It is still not possible to create two list with the same _name. This is problemetic for the default lists. I still got the duplicate key error for default lists and editing the name of the list.

**Comment by juanmi108** [comment]
yes you can, you cannot create a document with the same _name and the same owner, that does not makes sense and the duplicate key error is thrown. 

the problem is still the controller. after passing the name of the list as the ":id" param for the url 
```javascript
$scope.update = function(){
              ListsEdit.update({id:$scope.list._name },{_name:$scope.list._name ,visibility:$scope.list.visibility,color:$scope.list.color})
               //window.location.replace('/');
          }
```
I created a couple of users (juanmi104 to juanmi106 :) ) and all got their default list, and I could change every single one of them without getting errors.
